# Baseline model

In [1]:
import pandas as pd

train_df = pd.read_csv("../data/proccessed/smish/train_df.csv")
test_df = pd.read_csv('../data/proccessed/smish/test_df.csv')
# train_df = pd.read_csv('train_df.csv')    # colab runtime
# test_df = pd.read_csv('test_df.csv')      # colab runtime

In [2]:
print(len(train_df))
print(len(test_df))

35331
7571


In [3]:
from hybrid_cse_system_v2.rbs.extractor import extract_rbs_features
# from rbs.extractor import extract_rbs_features    # colab runtime


train_ = []
test_ = []

for _, row in train_df.iterrows():
    features = extract_rbs_features(row['TEXT'])
    train_.append(features)

for _, row in test_df.iterrows():
    features = extract_rbs_features(row['TEXT'])
    test_.append(features)

In [4]:
X_rbs_train = pd.DataFrame(train_)
X_rbs_test = pd.DataFrame(test_)

In [5]:
X_rbs_train.head()

,url_count,has_url,suspicious_tld_count,phone_count,has_phone,known_smishing_phrase_hits,urgency_term_hits,reward_term_hits,text_length,token_estimate,digit_ratio,numeric_token_count,short_code_count,uppercase_ratio,repeated_punct_count,proximity_suspicious_hits
0,0,0,0,0,0,0,0,0,139,30,0.122302,3,0,0.035971,0,0
1,0,0,0,0,0,2,0,0,499,79,0.004008,1,0,0.058116,0,3
2,0,0,0,0,0,0,0,1,187,41,0.010695,1,0,0.026738,0,0
3,0,0,0,0,0,0,1,0,53,11,0.000000,0,0,0.037736,0,0
4,0,0,0,0,0,0,0,0,92,17,0.000000,0,0,0.032609,0,0


# TD-IDF Text representation

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    ngram_range=(1, 2),
    max_features=1000,
    min_df=3
)

X_train_tfidf = tfidf_vectorizer.fit_transform(train_df['TEXT'])
X_test_tfidf = tfidf_vectorizer.transform(test_df['TEXT'])

In [7]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(35331, 1000)
(7571, 1000)


In [8]:
len(tfidf_vectorizer.vocabulary_)

1000

In [9]:
feature_names = tfidf_vectorizer.get_feature_names_out()
print(feature_names[:-20])

['00' '000' '10' '10 000' '10 order' '10 orders' '10 purchase' '100'
 '1000' '12' '123' '1234567890' '15' '150p' '16' '18' '20' '20 purchase'
 '24' '24 hours' '25' '30' '50' '500' '5000' '800' 'abc' 'ac' 'access'
 'account' 'account compromised' 'account flagged' 'account security'
 'acount' 'act' 'act fast' 'act quickly' 'action' 'action required'
 'activate' 'activities' 'activity' 'activity account' 'activity click'
 'actual' 'actually' 'ad' 'add' 'additional' 'address' 'advantage' 'ahead'
 'ai' 'ake' 'al' 'alert' 'alert 10' 'alert 20' 'alert 50'
 'alert exclusive' 'alert free' 'amazing' 'amazing deals'
 'amazing opportunity' 'amazing prizes' 'amazon' 'amazon gift' 'amp'
 'answer' 'app' 'apply' 'asap' 'ask' 'attachments' 'attempt' 'attempts'
 'attention' 'automated' 'available' 'avoid' 'await' 'award' 'awarded'
 'away' 'awesome' 'ay' 'babe' 'bad' 'bait' 'balance' 'bank' 'believe'
 'best' 'best regards' 'better' 'beware' 'bg' 'bi' 'big' 'big exclusive'
 'big prizes' 'birthday' 'bit' 

In [10]:
# combine rbs features with tf-idf train values
from scipy.sparse import hstack

X_train_combined  = hstack([X_train_tfidf, X_rbs_train.values])
X_test_combined   = hstack([X_test_tfidf, X_rbs_test.values])

### Baseline System: RBS and Multinomial Naive Bayes

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

class RBSTransformer(BaseEstimator, TransformerMixin):
  def __init__(self, extractor):
    self.extractor = extractor

  def fit(self, X, y=None):
    return self

  def transform(self, x):
    features = [self.extractor(text) for text in x]
    df = pd.DataFrame(features)
    return df.values

In [12]:
from sklearn.pipeline import Pipeline, FeatureUnion

hybrid_features = FeatureUnion([
    ('tfidf', tfidf_vectorizer),
    ('rbs', RBSTransformer(extract_rbs_features)),
])
pipeline = Pipeline([
    ('features', hybrid_features),
    ('classifier', MultinomialNB()),
])

In [13]:
y_train = train_df['LABEL']
y_test = test_df['LABEL']

y_train_mapped = y_train.map({'ham': 0, 'spam': 1, 'smish': 2})
y_test_mapped = y_test.map({'ham': 0, 'spam': 1, 'smish': 2})

In [14]:
pipeline.fit(train_df['TEXT'], y_train_mapped)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('features', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"transformer_list transformer_list: list of (str, transformer) tuplesList of transformer objects to be applied to the data. The firsthalf of each tuple is the name of the transformer. The transformer canbe 'drop' for it to be ignored or can be 'passthrough' for features tobe passed unchanged... versionadded:: 1.1 Added the option `""passthrough""`... versionchanged:: 0.22 Deprecated `None` as a transformer in favor of 'drop'.","[('tfidf', ...), ('rbs', ...)]"
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"transformer_weights transformer_weights: dict, default=NoneMultiplicative weights for features per transformer.Keys are transformer names, values the weights.Raises ValueError if key not present in ``transformer_list``.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each transformer will beprinted as it is completed.",False
,"verbose_feature_names_out verbose_feature_names_out: bool, default=TrueIf True, :meth:`get_feature_names_out` will prefix all feature nameswith the name of the transformer that generated that feature.If False, :meth:`get_feature_names_out` will not prefix any featurenames and will error if feature names are not unique... versionadded:: 1.5",True
,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'


In [15]:
probs = pipeline.predict_proba(test_df['TEXT'])

In [16]:
probs[:3]

array([[0.43613285, 0.25949296, 0.30437419],
       [0.99648624, 0.00146257, 0.00205119],
       [0.21925818, 0.02965222, 0.75108961]])

In [17]:
y_test[:3]

0      ham
1      ham
2    smish
Name: LABEL, dtype: object

In [18]:
smish_risk = probs[:, 2]

In [19]:
smish_risk

array([0.30437419, 0.00205119, 0.75108961, ..., 0.46823669, 0.06881855,
       0.03612857], shape=(7571,))

In [20]:
y_pred = pipeline.predict(test_df['TEXT'])
y_pred_proba = probs

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test_mapped, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      3625
           1       0.91      0.87      0.89      1797
           2       0.89      0.93      0.91      2149

    accuracy                           0.94      7571
   macro avg       0.92      0.92      0.92      7571
weighted avg       0.94      0.94      0.94      7571



In [22]:
conf_matrix = confusion_matrix(y_test_mapped, y_pred)
conf_matrix

array([[3516,   61,   48],
       [  44, 1561,  192],
       [  43,  102, 2004]])

In [23]:
import numpy as np

print("Mean risk for true smish:", np.mean(smish_risk[y_test == 2]))
print("Mean risk for ham:", np.mean(smish_risk[y_test == 0]))
print("Mean risk for spam:", np.mean(smish_risk[y_test == 1]))

Mean risk for true smish: nan
Mean risk for ham: nan
Mean risk for spam: nan


/home/shesham/.cache/pypoetry/virtualenvs/hybrid-cse-system-v2-gI9y8bRM-py3.14/lib64/python3.14/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/shesham/.cache/pypoetry/virtualenvs/hybrid-cse-system-v2-gI9y8bRM-py3.14/lib64/python3.14/site-packages/numpy/_core/_methods.py:144: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [24]:
from sklearn.metrics import roc_auc_score

binary_true = (y_test_mapped == 2).astype(int)
binary_scores = y_pred_proba[:, 2]

roc_auc_score(binary_true, binary_scores)

0.9836573984039311

### TF-IDF Only Pipeline
This is to verify if the RBS is actually helping the model or just adding noise

In [25]:
tfidf_only_pipeline = Pipeline([
    ("tfidf", tfidf_vectorizer),
    ("classifier", MultinomialNB())
])

tfidf_only_pipeline.fit(train_df["TEXT"], y_train_mapped)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('tfidf', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (string transformation) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None


In [26]:
y_pred_tfidf = tfidf_only_pipeline.predict(test_df["TEXT"])
y_probs_tfidf = tfidf_only_pipeline.predict_proba(test_df["TEXT"])

In [27]:
y_pred_tfidf[1]

np.int64(0)

In [28]:
y_probs_tfidf[1]

array([0.98245007, 0.00588636, 0.01166357])

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print(classification_report(y_test_mapped, y_pred_tfidf))

binary_true = (y_test_mapped == 2).astype(int)
binary_scores_tfidf = y_probs_tfidf[:, 2]
print(roc_auc_score(binary_true, binary_scores_tfidf))

conf_matrix = confusion_matrix(y_test_mapped, y_pred_tfidf)
print(conf_matrix)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      3625
           1       0.93      0.88      0.91      1797
           2       0.91      0.91      0.91      2149

    accuracy                           0.93      7571
   macro avg       0.93      0.92      0.93      7571
weighted avg       0.93      0.93      0.93      7571

0.9842082108995648
[[3522   38   65]
 [  74 1590  133]
 [ 110   76 1963]]


In detecting smish messages, the hybrid model scores a lower precison of 0.89 while the tfidf-only model scores a precision of 0.90. But in terms of recall, the hybrid model does better with a score of 0.95, while the tfidf model scores 0.93. This is likely because rules, which the hybrid has, are built to improve recall.

In [30]:
# checking for ovelaps(duplicates across data splits)

train_texts = set(train_df["TEXT"])
test_texts = set(test_df["TEXT"])

overlap = train_texts.intersection(test_texts)
len(overlap)

0

In [31]:
print(f"{(1105 / 8400):.2f}")

0.13


In [38]:
import joblib

# freeze weights
joblib.dump(pipeline, "../models/hybrid_pipeline.joblib")
joblib.dump(tfidf_only_pipeline, "../models/tfidf_pipeline.joblib")

['../models/tfidf_pipeline.joblib']

In [32]:
# using manually combined tfidf vector and rbs features

mnb = MultinomialNB()
mnb.fit(X_train_combined, y_train_mapped)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [33]:
mnb_preds = mnb.predict(X_test_combined)
mnb_proba = mnb.predict_proba(X_test_combined)

In [37]:
print(mnb_preds[2])
print(mnb_proba[2])

2
[0.21925818 0.02965222 0.75108961]


In [36]:
print(classification_report(y_test_mapped, mnb_preds))

binary_true = (y_test_mapped == 2).astype(int)
binary_scores_tfidf = mnb_proba[:, 2]
print(roc_auc_score(binary_true, binary_scores_tfidf))

conf_matrix = confusion_matrix(y_test_mapped, mnb_preds)
print(conf_matrix)

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      3625
           1       0.91      0.87      0.89      1797
           2       0.89      0.93      0.91      2149

    accuracy                           0.94      7571
   macro avg       0.92      0.92      0.92      7571
weighted avg       0.94      0.94      0.94      7571

0.9836573984039311
[[3516   61   48]
 [  44 1561  192]
 [  43  102 2004]]


In [41]:
joblib.dump(mnb, "../models/mnb_model.joblib")
joblib.dump(tfidf_vectorizer, "../models/tfidf_vectorizer.joblib")

['../models/tfidf_vectorizer.joblib']